junior_hr(hoang).
junior_hr(minh).
junior_hr(long).
junior_hr(ngoc).
junior_hr(lan).
junior_dev(tuan).
junior_dev(khang).
junior_dev(linh).
junior_dev(vu).
junior_sale(hien).
junior_sale(chi).
junior_sale(vuong).
junior_sale(thanh).
quanli(hong,hoang).
quanli(hong,minh).
quanli(hong,long).
quanli(hong,ngoc).
quanli(hong,lan).
quanli(thu,hoang).
quanli(thu,minh).
quanli(thu,long).
quanli(thu,ngoc).
quanli(thu,lan).
quanli(lam,hoang).
quanli(lam,minh).
quanli(lam,long).
quanli(lam,ngoc).
quanli(lam,lan).
quanli(thinh,tuan).
quanli(thinh,khang).
quanli(thinh,linh).
quanli(thinh,vu).
quanli(an,tuan).
quanli(an,khang).
quanli(an,linh).
quanli(an,vu).
quanli(nhat,tuan).
quanli(nhat,khang).
quanli(nhat,linh).
quanli(nhat,vu).
quanli(diem,hien).
quanli(diem,chi).
quanli(diem,vuong).
quanli(diem,thanh).
quanli(my,hien).
quanli(my,chi).
quanli(my,vuong).
quanli(my,thanh).
quanli(dieu,hien).
quanli(dieu,chi).
quanli(dieu,vuong).
quanli(dieu,thanh).
quanli(lieu,hong).
quanli(lieu,thu).
quanli(lieu,lam).
quanli(tan,thinh).
quanli(tan,an).
quanli(tan,nhat).
quanli(hoa,diem).
quanli(hoa,my).
quanli(hoa,dieu).
quanli(chau,lieu).
quanli(chau,tan).
quanli(chau,hoa).
junior(X):-junior_hr(X);junior_dev(X);junior_sale(X).
senior_hr(X):-quanli(X,Y),junior_hr(Y).
senior_dev(X):-quanli(X,Y),junior_dev(Y).
senior_sale(X):-quanli(X,Y),junior_sale(Y).
senior(X):-senior_hr(X);senior_dev(X);senior_sale(X).
truongphong_hr(X):-quanli(X,Y),senior_hr(Y).
truongphong_dev(X):-quanli(X,Y),senior_dev(Y).
truongphong_sale(X):-quanli(X,Y),senior_sale(Y).
truongphong(X):-truongphong_hr(X);truongphong_sale(X);truongphong_dev(X).
giamdoc(X):-quanli(X,Y),truongphong(Y).
cungcapbac(X,Y):-(junior(X),junior(Y));(senior(X),senior(Y));(truongphong(X),truongphong(Y)).
thuocbophan_hr(X):-junior_hr(X);senior_hr(X);truongphong_hr(X).
thuocbophan_dev(X):-junior_dev(X);senior_dev(X);truongphong_dev(X).
thuocbophan_sale(X):-junior_sale(X);senior_sale(X);truongphong_sale(X).
cungbophan(X,Y):-(thuocbophan_hr(X),thuocbophan_hr(Y));(thuocbophan_dev(X),thuocbophan_dev(Y));(thuocbophan_sale(X),thuocbophan_sale(Y)).
nhanvien(X):-thuocbophan_hr(X);thuocbophan_dev(X);thuocbophan_sale(X).
captren(X,Y):-(giamdoc(X),nhanvien(Y));(senior(X),junior(Y),cungbophan(X,Y));(truongphong(X),senior(Y),cungbophan(X,Y));(truongphong(X),junior(Y),cungbophan(X,Y)).
capduoi(X,Y):-captren(Y,X).


